runtime: custom
env: flex

network:
  name: new-default
  instance_ip_mode: internal 
  subnetwork_name: new-default
  session_affinity: true

manual_scaling:
  instances: 1

handlers:
- url: /.*
  static_files: index.html
  upload: index.html
  secure: always